.TH RENEW-ALL 1 "January 11, 2012"
.SH NAME
renew-all \- renew all tickets in a DIR cache
.SH SYNOPSIS
renew-all
.SH DESCRIPTION
.IR renew-all
fetches long-lived (7 day, if available) renewable tickets for all caches in
the current DIR cache collection. It will restore the primary cache to its
original state at the end.

.SH BUGS
Please report to bug-sipb@mit.edu.

.SH AUTHORS
Alex Dehnert (adehnert)
